# Generated by Django 4.0.3 on 2022-04-11 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Business name', max_length=64, verbose_name='Business name')),
                ('about', models.TextField(blank=True, default='', null=True, verbose_name='About business')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='+353', max_length=16, null=True)),
                ('telegram', models.CharField(blank=True, default='account_name', max_length=24, null=True)),
                ('insta', models.CharField(blank=True, default='account_name', max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Business field')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'business_field',
            },
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='County')),
            ],
            options={
                'db_table': 'counties',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Service')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.business')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='City')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty.counties')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty.city'),
        ),
        migrations.AddField(
            model_name='business',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty.counties'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='type_of_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty.businessfield'),
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=48, null=True, verbose_name='First name')),
                ('uid', models.PositiveBigIntegerField()),
                ('language', models.CharField(blank=True, max_length=8, null=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('date_reg', models.DateTimeField(blank=True, null=True, verbose_name='Registration date')),
                ('connect_date', models.DateTimeField(blank=True, null=True, verbose_name='Last connection date')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty.counties')),
            ],
        ),
    ]
