# Generated by Django 4.0.3 on 2022-04-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_botuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='business_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty.businessfield'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='search',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
