# Generated by Django 4.0.3 on 2022-04-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_business_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='type_of_business',
        ),
    ]
