# Generated by Django 4.0.3 on 2022-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_alter_service_owner_remove_service_type_of_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='about',
            field=models.TextField(default='', verbose_name='About business'),
        ),
    ]
