# Generated by Django 4.0.3 on 2022-04-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_service_email_service_phone_service_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='business_field',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='beauty.service'),
        ),
    ]
