# Generated by Django 4.0.3 on 2022-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0005_remove_servicetype_business_field_servicetype_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
