# Generated by Django 4.0.3 on 2022-04-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0006_remove_business_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty.city'),
        ),
        migrations.AddField(
            model_name='business',
            name='type_of_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty.businessfield'),
        ),
    ]
