# Generated by Django 4.0.3 on 2022-04-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0006_servicetype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.service'),
        ),
    ]
