# Generated by Django 4.0.3 on 2022-04-02 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beauty', '0007_alter_servicetype_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Business',
        ),
    ]
