# Generated by Django 4.0.3 on 2022-04-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0007_business_city_business_type_of_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about',
            field=models.TextField(blank=True, default='', null=True, verbose_name='About business'),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='insta',
            field=models.CharField(blank=True, default='account_name', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, default='+353', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='telegram',
            field=models.CharField(blank=True, default='account_name', max_length=24, null=True),
        ),
    ]
