# Generated by Django 4.0.3 on 2022-04-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0008_rename_service_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='insta',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
