# Generated by Django 4.0.3 on 2022-04-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0008_business_about_business_email_business_insta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='business',
            name='telegram',
        ),
    ]
