# Generated by Django 4.0.3 on 2022-04-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0010_alter_business_about_alter_business_type_of_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='insta',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, default='+353', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
    ]
